version: '3'
services:
  nodered:
    container_name: objectpath-nodered
    image: nodered/node-red:latest
    restart: always
    environment:
      - TZ=Europe/Stockholm
    ports:
      - '8640:1880'
    links:
      - mongodb
    volumes:
      - ./:/data
  mongodb:
    container_name: objectpath-mongodb
    image: mongo:4.4.14
    restart: always
#    ports:
#      - 27017:27017
    environment:
     - MONGODB_AUTH=false
    volumes:
      - ./mongodb:/data/db

